# Generated by Django 4.2.16 on 2024-09-06 20:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('price', models.CharField(max_length=1000)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(blank=True, max_length=20)),
                ('company_gst', models.CharField(blank=True, max_length=16)),
                ('company_address_line1', models.CharField(blank=True, max_length=20)),
                ('company_address_line2', models.CharField(blank=True, max_length=20)),
                ('company_city', models.CharField(blank=True, max_length=20)),
                ('company_state', models.CharField(blank=True, max_length=15)),
                ('company_pincode', models.CharField(blank=True, max_length=20)),
                ('account_name', models.CharField(blank=True, max_length=20, null=True)),
                ('account', models.CharField(blank=True, max_length=20, null=True)),
                ('ifsc', models.CharField(blank=True, max_length=11, null=True)),
                ('phone_number', models.CharField(blank=True, default='phone', max_length=10, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('gst', models.CharField(default=None, max_length=16, null=True)),
                ('email', models.CharField(blank=True, max_length=25, null=True)),
                ('phone', models.CharField(max_length=15)),
                ('address_line1', models.CharField(blank=True, max_length=20, null=True)),
                ('address_line2', models.CharField(blank=True, max_length=20, null=True)),
                ('city', models.CharField(blank=True, max_length=20, null=True)),
                ('state', models.CharField(blank=True, max_length=15, null=True)),
                ('pincode', models.CharField(blank=True, max_length=6, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
